### ISSUE TITLE
Add third official DLC "Far Harbor" to the masterlist

### ISSUE THREAD

**Issue by pStyl3** [loot/fallout4#15]
DLCCoast.esm

**Comment by Ortham** [comment]
Does it always load like the other DLC plugins?

**Comment by Freso** [comment]
I believe it does, but we should still include it to prevent users unknowingly drag-dropping it somewhere random in their load order.

**Comment by Freso** [comment]
Hm. I guess we don't have the other ones currently, so maybe it isn't needed? Can I summon @Arthmoor for feedback perhaps? (Should the official DLCs be included at this point?)

**Comment by Arthmoor** [comment]
Yes. All DLCs autoload if the files are installed. There is no way to turn that off via the game's UI.

Official DLC should still be listed in the order they were released since using Bethesda's internal load order function still doesn't put the DLCs into the correct slots when the game loads if there are user generated ESM files active.

It will, however, load them in the correct order if plugins.txt specifies them and the user stays out of the Mods menu in the game.

**Comment by Freso** [comment]
Thanks @Arthmoor for confirming. :) (Also, looks like I was being blind: the other two DLCs were already in the list.)

**Comment by pStyl3** [comment]
Thanks to everyone. :+1:
