### ISSUE TITLE
Needs about a million mods added to the masterlist...

### ISSUE THREAD

**Issue by drakesteele** [loot/fallout4#4]
If I knew how I'd try to help with this but I'm amazed that as popular as this is, previous masterlist contributors haven't been piling their load order learnings onto this list... Are you all waiting for the new GECK?

**Comment by unforbidable** [comment]
I'm not a past or current contributor but I don't mind adding plugins to the master list and likely will have some time during the holidays. A million plugins sounds like a lot of work so getting head start seems like a good idea. Perhaps start with stable plugins which get "refactored" rarely.

I am not authority but I believe you can help by creating new issues here. That sounds like a good start  and quite a tedious task to me.

**Comment by WrinklyNinja** [comment]
> If I knew how I'd try to help with this

Luckily for you there is a [CONTRIBUTING.md](https://github.com/loot/fallout4/blob/v0.8/CONTRIBUTING.md) file that explains how to do just that.

> Are you all waiting for the new GECK?

I suspect nearly everyone is waiting for everyone else to DIY, but otherwise you can help by filing more useful issues: #1 and #2 are good examples of how to do so well, notice how they give details rather than just stating "a million mods".

You should also note that plugins shouldn't get added to the masterlist unless there is useful metadata to add for them. The tone of your comment suggests you're confusing LOOT's masterlists with BOSS's, to which all plugins did need to be added.

**Comment by Freso** [comment]
> You should also note that plugins shouldn't get added to the masterlist unless there is useful metadata to add for them.

Adding on to this: The current state of the masterlist is largely based on mods I've been in contact with. I'm probably using 5-10 times as many .esp files than what I've added here, but LOOT handles all of those correctly, based entirely on what LOOT can glean directly from the .esp/.esm files themselves, thus there's no need to add them to the LOOT masterlist.

I'm closing this issue. Please open new issues for specific mods that need special handling by LOOT.
