### ISSUE TITLE
Better Settlers forced to load AFTER scrap everything

### ISSUE THREAD

**Issue by IDCs** [loot/fallout4#426]
Hi there - I'm just looking for clarification on why it's important for Better Settlers to load after Scrap Everything; not going to lie, I'm not very familiar with either mods but they seem unrelated, bar the fact that loading Scrap Everything AFTER Better Settlers would probably allow you to scrap dead settlers - I'm assuming that's the core of the problem for some reason. But if it's not, I'd like to submit a pull request to remove this restriction.
https://github.com/loot/fallout4/blob/7e14d7d5063527ffad9b5b8ba047c11c0467cbac/masterlist.yaml#L3962

One of our Vortex users https://github.com/Nexus-Mods/Vortex/issues/10928 has been trying to reverse the order of these two mods which he obviously can't due to this rule.

Any information regarding this restriction would be greatly appreciated!

**Comment by sibir-ine** [comment]
I assume it's due to Scrap Everything overwriting Better Settlers' changes in several NPCs by just adding a name:

![image](https://user-images.githubusercontent.com/69141501/152207528-6227efc3-f9ee-44f6-9297-311ac499ba8a.png)

One of the authors of SE also addressed the conflict, [stating](https://forums.nexusmods.com/index.php?/topic/3527530-scrap-everything/page-406#entry60005051) as much. Considering so many of these changes are just adding names & that it seems excessive to load a mod so late when the consequence of not doing so is just that not everything will work as expected (as will probably be the case with all of the mods it overwrites, such as Better Settlers), SE should probably be moved back to `default` at some point. Load afters can then be added for plugins it really needs to load after.

However, more investigation will probably be needed. For the matter at hand, one of the authors of SE said it's fine to load Better Settlers after SE, but I can see how it could cause issues for it to be hoisted so late in the load order as a result of SE's group. The load after can be removed in the interim as LOOT's algorithm would probably sort Better Settlers after SE with a soft [overlap rule](https://loot.readthedocs.io/en/stable/app/sorting.html#overlap-rules) if SE is moved back to default, so feel free to remove it.

**Comment by IDCs** [comment]
Thank you for the clarification @sibir-ine - I've created a pull request to remove the rule. Feel free to close this issue if the PR can be merged in.
